services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "investing"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    ports:
      - "5432:5432"
    volumes:
        - ./:/app

  redis:
    image: redis
    ports:
      - "6379:6379"
