# Generated by Django 4.1.7 on 2023-03-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("figi", models.CharField(max_length=255)),
                ("isin", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("ticker", models.CharField(max_length=10)),
                ("currency", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
    ]
