# Generated by Django 4.1.7 on 2023-03-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_update_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="uid",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
