# Generated by Django 4.1.7 on 2023-03-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_add_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="is_trend_high",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Растет цена"
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="last_price",
            field=models.FloatField(blank=True, null=True, verbose_name="Текущая цена"),
        ),
        migrations.AlterField(
            model_name="share",
            name="currency",
            field=models.CharField(max_length=20, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="share",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="share",
            name="ticker",
            field=models.CharField(max_length=10, unique=True, verbose_name="Ти"),
        ),
    ]
