# Generated by Django 4.1.7 on 2023-03-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_add_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="share",
            name="ticker",
            field=models.CharField(max_length=10, unique=True, verbose_name="Тикер"),
        ),
    ]
